name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o codigo do projeto
        uses: actions/checkout@v4
      - name: Autenticar no docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            hogsidney/fake-shop:latest
            hogsidney/fake-shop:v${{ github.run_mumber }}
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na aws
        run: echo "Executando o comando aws configure"
      - name: configurar o kubetctl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy do mainifestos Kubernetes
        run: echo "Executando o comando kubectl apply"
